---
- name: Enable and start Hypershield agent service
  ansible.builtin.service:
    name: "{{ hypershield_service_name }}"
    enabled: "{{ hypershield_service_enabled }}"
    state: "{{ hypershield_service_state }}"
  become: true
