---
# Internal variables - do not override

hypershield_valid_severities:
  - "critical"
  - "high"
  - "medium"
  - "low"
  - "info"
hypershield_valid_compliance_frameworks:
  - "pci-dss"
  - "hipaa"
  - "nist-800-53"
  - "soc2"
  - "iso-27001"
