---
galaxy_info:
  role_name: dpusetup
  author: Steve Fulmer
  description: NVIDIA BlueField DPU security configuration for Cisco Hypershield
  company: Red Hat
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - cisco
    - hypershield
    - nvidia
    - bluefield
    - dpu
    - security

dependencies: []
